services:
  db:
    image: postgres:16
    container_name: mealsteals-dealfinder-db
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=dealfinder
    ports:
      - "5432:5432"
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    container_name: mealsteals-dealfinder-api
    build:
      context: ./dealfinder
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./dealfinder:/app
    environment:
      - ENVIRONMENT=dev
      - DATABASE_USER=postgres
      - DATABASE_PASS=password
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_NAME=dealfinder
    networks:
      - app-network
    depends_on:
      db:
        condition: service_healthy
  
  #  # Development Web build
  #  web:
  #    container_name: web
  #    build:
  #      context: ./apps/web
  #      dockerfile: Dockerfile
  #    ports:
  #      - "3000:3000"
  #    volumes:
  #      - ./apps/web:/app
  #    environment:
  #      - ENVIRONMENT=dev
  #    networks:
  #      - app-network
  #
networks:
  app-network:
    driver: bridge

volumes:
  db-data:


