services:
  dealapi:
    container_name: mealsteals-dealAPI
    build:
      context: ./dealAPI
      dockerfile: Dockerfile
    command: uvicorn app.main:app --host 0.0.0.0 --port 5000 --reload
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-ap-southeast-2}
      - RESTAURANT_TABLE_NAME=${RESTAURANT_TABLE_NAME:-mealsteals-dealdb-restaurants}
      - DEAL_TABLE_NAME=${DEAL_TABLE_NAME:-mealsteals-dealdb-deals}
      - DEAL_SCRAPING_QUEUE_URL=${DEAL_SCRAPING_QUEUE_URL:-https://sqs.ap-southeast-2.amazonaws.com/700723066985/mealsteals-dealscraper-queue}
    ports:
      - "5000:5000"
    volumes:
      - ./dealAPI/app:/code/app
      - ./dealAPI/.venv:/code/.venv
    networks:
      - app-network
  
  dealmapper:
    container_name: mealsteals-dealMapper
    build:
      context: ./dealmapper
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./dealmapper:/app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data:

secrets:
  pip_config:
    file: /etc/pip.conf
