"""Make address fields optional for now

Revision ID: 01ba0d842726
Revises: cd8cc6c08265
Create Date: 2025-02-16 13:58:47.611097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01ba0d842726'
down_revision = 'cd8cc6c08265'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.alter_column('suburb',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('state',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('postcode',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('country',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.alter_column('country',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('postcode',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('state',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('suburb',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
