"""Create deals last_updated field

Revision ID: 57e8a41f513b
Revises: 7c7e2c275b46
Create Date: 2025-03-03 07:27:24.129320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57e8a41f513b'
down_revision = '7c7e2c275b46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('last_updated', sa.DateTime(timezone=True), nullable=False))
        batch_op.drop_column('note')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('note', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_column('last_updated')
        batch_op.drop_column('notes')

    # ### end Alembic commands ###
