"""Make URL not unique

Revision ID: 7c7e2c275b46
Revises: 01ba0d842726
Create Date: 2025-02-17 07:21:48.545850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c7e2c275b46'
down_revision = '01ba0d842726'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.drop_constraint('restaurant_url_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.create_unique_constraint('restaurant_url_key', ['url'])

    # ### end Alembic commands ###
