"""Create deal hash

Revision ID: a4edaa6c8318
Revises: c267e527659f
Create Date: 2025-03-04 06:36:02.476443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4edaa6c8318'
down_revision = 'c267e527659f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deal_hash', sa.String(), nullable=False))
        batch_op.create_unique_constraint(None, ['deal_hash'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deal', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('deal_hash')

    # ### end Alembic commands ###
