"""Make deals components optional

Revision ID: ed0e170b8ec7
Revises: 57e8a41f513b
Create Date: 2025-03-03 21:00:19.955389

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ed0e170b8ec7'
down_revision = '57e8a41f513b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deal', schema=None) as batch_op:
        batch_op.alter_column('day_of_week',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=True)
        batch_op.alter_column('notes',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deal', schema=None) as batch_op:
        batch_op.alter_column('notes',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('day_of_week',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=False)

    # ### end Alembic commands ###
