"""restaurants table

Revision ID: eea0316ac44b
Revises: 
Create Date: 2025-01-06 16:11:44.659128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eea0316ac44b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('cuisine', sa.String(), nullable=True),
    sa.Column('venue_type', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('latitude', sa.DECIMAL(), nullable=False),
    sa.Column('longitude', sa.DECIMAL(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_restaurant_latitude'), ['latitude'], unique=False)
        batch_op.create_index(batch_op.f('ix_restaurant_longitude'), ['longitude'], unique=False)
        batch_op.create_index(batch_op.f('ix_restaurant_name'), ['name'], unique=False)

    op.create_table('deal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('dish', sa.String(), nullable=True),
    sa.Column('price', sa.DECIMAL(), nullable=True),
    sa.Column('day_of_week', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('note', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('deal', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deal_dish'), ['dish'], unique=False)
        batch_op.create_index(batch_op.f('ix_deal_price'), ['price'], unique=False)
        batch_op.create_index(batch_op.f('ix_deal_restaurant_id'), ['restaurant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deal', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deal_restaurant_id'))
        batch_op.drop_index(batch_op.f('ix_deal_price'))
        batch_op.drop_index(batch_op.f('ix_deal_dish'))

    op.drop_table('deal')
    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_restaurant_name'))
        batch_op.drop_index(batch_op.f('ix_restaurant_longitude'))
        batch_op.drop_index(batch_op.f('ix_restaurant_latitude'))

    op.drop_table('restaurant')
    # ### end Alembic commands ###
